modLoader="javafml"
loaderVersion="[47,]" # Forge for MC 1.20.1 usually requires loader version 45+
license="All rights reserved"

[[mods]]
modId="udi"
version="1.0.1"
displayName="UndroppableItem"
description='''
Adds the ability to disable specified item from dropped or moved away from inventory
'''
authors="neiru1"
# logoFile="path_to_logo.png"  # Optional: path to your mod logo file

[[dependencies.udi]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.udi]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
